include: package:lints/recommended.yaml
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
linter:
  rules:
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - sized_box_for_whitespace
    - sort_child_properties_last
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors
    - always_use_package_imports
    - avoid_returning_null_for_future
    - avoid_type_to_string
    - comment_references
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - avoid_final_parameters
    - avoid_multiple_declarations_per_line
    - avoid_redundant_argument_values
    - avoid_returning_null
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - flutter_style_todos
    - no_default_cases
    - no_runtimeType_toString
    - prefer_null_aware_method_calls
    - require_trailing_commas
    - unnecessary_await_in_return
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - use_if_null_to_convert_nulls_to_bools
    - prefer_if_elements_to_conditional_expressions
    - always_declare_return_types
    - avoid_bool_literals_in_conditional_expressions
    - always_put_control_body_on_new_line
    - avoid_setters_without_getters
    - cast_nullable_to_non_nullable
    - avoid_dynamic_calls
    - cancel_subscriptions
    - close_sinks
    - unawaited_futures
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - always_put_required_named_parameters_first
    - avoid_annotating_with_dynamic
    - avoid_double_and_int_checks
    - avoid_field_initializers_in_const_classes
    - avoid_implementing_value_types
    - avoid_js_rounded_ints
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_positional_boolean_parameters
    - conditional_uri_does_not_exist
    - deprecated_consistency
    - noop_primitive_operations
    - omit_local_variable_types
    - one_member_abstracts
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_int_literals
    - type_annotate_public_apis
    - use_decorated_box
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_setters_to_change_properties
    - use_string_buffers
    # - public_member_api_docs
    # - lines_longer_than_80_chars
    # - package_api_docs
    # - use_build_context_synchronously
    

analyzer:
  exclude:
    - lib/model/**.g.dart
    - lib/packages/**
    - lib/widget/comm_menu_widget.dart
