name: dcm
version: 1.8.0
homepage: https://github.com/josercc/dcm
description: Dart CLI manager
environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  args: ^2.3.1
  darty_json_safe: ^1.0.0
  json_annotation: ^4.6.0
  mustache_template: ^2.0.0
  path: ^1.8.2
  process_run: ^0.12.3+2
  pubspec_parse: ^1.2.1
  yaml: ^3.1.1
  io: ^1.0.3
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
executables:
  dcm:
