name: dcm
description: Dart CLI manager
version: 1.0.0
# homepage: https://www.example.com

executables:
  dcm:

environment:
  sdk: '>=2.12.2 <3.0.0'

dependencies: 
  args: ^2.3.1
  darty_json_safe: ^0.2.0
  mustache4dart: ^3.0.0-dev.0.0
  process_run: ^0.12.3+2
  pubspec_parse: ^1.2.1
  

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
