name: dart_cli_manager
description: Dart CLI manager
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.2 <3.0.0'

dependencies: 
  args: ^2.3.1
  darty_json_safe: ^0.2.0
  process_run: ^0.12.3+2
  

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
